# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:39
from __future__ import unicode_literals

import decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=255)),
                ('limite', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('caja', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('fecha_en_factura', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_de_factura', models.CharField(default='', max_length=255)),
                ('fecha_maxima_de_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('factura', models.FileField(blank=True, null=True, upload_to='budget/gasto/%Y/%m/%d')),
                ('numero_de_comprobante_de_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('comprobante_de_pago', models.FileField(blank=True, null=True, upload_to='budget/gasto/%Y/%m/%d')),
                ('fecha_de_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('ejecutado', models.BooleanField(default=False)),
                ('numero_pagos', models.IntegerField(default=1)),
                ('recepcion_de_facturas_originales', models.BooleanField(default=False)),
                ('fecha_de_recepcion_de_factura', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Cuenta', verbose_name='Tipo de Cargo')),
                ('fuente_de_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Fuente')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('activo', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ciudad')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('activo', models.BooleanField(default=True)),
                ('porcentaje_global', models.DecimalField(decimal_places=2, default=decimal.Decimal, max_digits=3)),
                ('inversion', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ciudad')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField(verbose_name='A\xf1o')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('procesado', models.BooleanField(default=False, verbose_name='Completar A\xf1o')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Cuenta')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Presupuesto'),
        ),
    ]
