# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20150928_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField(verbose_name='A\xf1o')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Cuenta')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='rubro',
        ),
        migrations.RemoveField(
            model_name='presupuestomensual',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='presupuesto',
        ),
        migrations.DeleteModel(
            name='Concepto',
        ),
        migrations.DeleteModel(
            name='PresupuestoMensual',
        ),
        migrations.DeleteModel(
            name='Rubro',
        ),
    ]
