# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20160113_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestomes',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
    ]
