# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='fin_rango_comprobante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='inicio_rango_comprobante',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
