# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160201_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
