# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 23:23
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_nombre_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cai', models.CharField(blank=True, max_length=255)),
                ('correlativo', models.IntegerField(default=0)),
                ('inicio', models.CharField(blank=True, max_length=100)),
                ('fin', models.CharField(blank=True, max_length=100)),
                ('prefijo', models.CharField(blank=True, max_length=100)),
                ('limite_de_emision', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='limite_de_emision_comprobante',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='comprobante',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_comprobante', to='users.LegalData'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nota_credito',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_nota_credito', to='users.LegalData'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='recibo',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_recibo', to='users.LegalData'),
        ),
    ]
