# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 23:47
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Ciudad = apps.get_model("users", "Ciudad")
    LegalData = apps.get_model("users", "LegalData")
    for ciudad in Ciudad.objects.all():
        recibo = LegalData()
        recibo.ciudad_creacion = ciudad
        recibo.correlativo = ciudad.correlativo_de_recibo
        recibo.cai = ciudad.cai_recibo
        recibo.prefijo = ciudad.prefijo_recibo
        recibo.limite_de_emision = ciudad.limite_de_emision
        recibo.inicio = ciudad.inicio_rango
        recibo.fin = ciudad.fin_rango
        recibo.tipo = 'R'
        recibo.save()
        ciudad.recibo = recibo

        comprobante = LegalData()
        comprobante.ciudad_creacion = ciudad
        comprobante.correlativo = ciudad.correlativo_de_comprobante
        comprobante.cai = ciudad.cai_comprobante
        comprobante.prefijo = ciudad.prefijo_comprobante
        comprobante.limite_de_emision = ciudad.limite_de_emision_comprobante
        comprobante.inicio = ciudad.inicio_rango_comprobante
        comprobante.fin = ciudad.fin_rango_comprobante
        comprobante.tipo = 'CD'
        comprobante.save()
        ciudad.comprobante = comprobante

        nota_credito = LegalData()
        nota_credito.ciudad_creacion = ciudad
        nota_credito.correlativo = ciudad.correlativo_de_nota_de_credito
        nota_credito.cai = ciudad.cai_nota_credito
        nota_credito.prefijo = ciudad.prefijo_nota_credito
        nota_credito.limite_de_emision = ciudad.limite_de_emision_nota_credito
        nota_credito.inicio = ciudad.inicio_rango_nota_credito
        nota_credito.fin = ciudad.fin_rango_nota_credito
        nota_credito.tipo = 'NC'
        nota_credito.save()
        ciudad.nota_credito = nota_credito

        ciudad.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160328_1723'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
