# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160328_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='cai_comprobante',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='cai_nota_credito',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='cai_recibo',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='correlativo_de_comprobante',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='correlativo_de_nota_de_credito',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='correlativo_de_recibo',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='fin_rango',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='fin_rango_comprobante',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='fin_rango_nota_credito',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='inicio_rango',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='inicio_rango_comprobante',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='inicio_rango_nota_credito',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='limite_de_emision',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='limite_de_emision_comprobante',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='limite_de_emision_nota_credito',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='prefijo_comprobante',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='prefijo_nota_credito',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='prefijo_recibo',
        ),
    ]
