# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160328_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='correo_laboratorio',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='sac',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
