# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_company_laboratorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='incapacidad_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
