# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='moneda',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
