# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20151213_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='cai_nota_credito',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='correlativo_de_nota_de_credito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='fin_rango_nota_credito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='inicio_rango_nota_credito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='limite_de_emision_nota_credito',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='prefijo_nota_credito',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
