# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import nightingale.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('facturada', models.NullBooleanField(default=False)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='spital.Admision')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='inventory.ItemTemplate')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('enfermeria', 'Permite al usuario gestionar hospitalizaciones'), ('enfermeria_ver', 'Permite al usuario ver datos')),
            },
            bases=(models.Model, nightingale.models.Precio),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='spital.Admision')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inventory.ItemTemplate')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'Rechazada'), (3, 'Administrada')], default=1, null=True)),
                ('recomendacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Excreta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio', models.CharField(blank=True, choices=[(b'S', 'Succi\xf3n'), (b'O', 'Orina'), (b'V', 'Vomito')], max_length=2)),
                ('cantidad', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('otro', models.CharField(blank=True, max_length=200)),
                ('otros', models.CharField(blank=True, max_length=200)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excretas', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excretas', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='FrecuenciaLectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucometria', models.IntegerField(blank=True, default=0)),
                ('signos_vitales', models.IntegerField(blank=True, default=0)),
                ('admision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spital.Admision')),
            ],
        ),
        migrations.CreateModel(
            name='Glicemia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('control', models.CharField(blank=True, max_length=200)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glicemias', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glicemias', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='Glucosuria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('control', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucosurias', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glucosurias', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medico', models.CharField(blank=True, max_length=200)),
                ('facturada', models.NullBooleanField(default=False)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorarios', to='spital.Admision')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honorarios', to='inventory.ItemTemplate')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honorarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Ingesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingerido', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.IntegerField()),
                ('liquido', models.NullBooleanField()),
                ('via', models.CharField(blank=True, max_length=200, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestas', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestas', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='Insulina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('control', models.CharField(blank=True, max_length=200)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insulina', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insulinas', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('intervalo', models.IntegerField(blank=True, choices=[(24, 'Cada 24 Horas'), (12, 'Cada 12 Horas'), (8, 'Cada 8 Horas'), (6, 'Cada 6 Horas'), (4, 'Cada 4 Horas')], null=True)),
                ('unidades', models.CharField(blank=True, max_length=200)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Activo'), (2, 'Suspendido'), (3, 'Terminado')], default=1, null=True)),
                ('ultima_dosis', models.DateTimeField(default=django.utils.timezone.now)),
                ('proxima_dosis', models.DateTimeField(default=django.utils.timezone.now)),
                ('suministrado', models.IntegerField(default=0)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='spital.Admision')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='inventory.ItemTemplate')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='NotaEnfermeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('cerrada', models.BooleanField(default=False)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_enfermeria', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_enfermeria', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolucion', models.TextField(blank=True)),
                ('orden', models.TextField(blank=True)),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_medicas', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_medicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OxigenoTerapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('terminada', models.BooleanField(default=False)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('facturada', models.NullBooleanField(default=False)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxigeno_terapias', to='spital.Admision')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oxigeno_terapias', to='inventory.ItemTemplate')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=(models.Model, nightingale.models.Precio),
        ),
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('pulso', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('presion_sistolica', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('presion_diastolica', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('respiracion', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('saturacion_de_oxigeno', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('presion_arterial_media', models.CharField(blank=True, max_length=200)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, nightingale.models.Turno),
        ),
        migrations.CreateModel(
            name='Sumario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('diagnostico', models.TextField(blank=True)),
                ('procedimiento_efectuado', models.TextField(blank=True)),
                ('condicion', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('admision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spital.Admision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sumarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='dosis',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosis', to='nightingale.Medicamento'),
        ),
        migrations.AddField(
            model_name='dosis',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosis', to=settings.AUTH_USER_MODEL),
        ),
    ]
