# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20160130_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercontract',
            options={'ordering': ['contratante__nombre']},
        ),
    ]
