# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20151123_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastercontract',
            name='item',
        ),
    ]
