# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:21
from __future__ import unicode_literals

from django.db import migrations
import persona.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_mastercontract_privado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='color',
            field=persona.fields.ColorField(default='', max_length=10),
        ),
    ]
