# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_mastercontract_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercontract',
            name='aseguradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Aseguradora'),
        ),
    ]
