# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20151213_1949'),
        ('contracts', '0007_auto_20151216_1128'),
    ]

    operations = [
    ]
