# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=200)),
                ('doctor', models.CharField(blank=True, max_length=200)),
                ('arancel', models.CharField(blank=True, choices=[(b'E', 'Empleado'), (b'J', 'Ejecutivo'), (b'X', 'Extranjero')], max_length=200)),
                ('pago', models.CharField(blank=True, choices=[(b'EF', 'Efectivo'), (b'CK', 'Cheque'), (b'CO', 'Empresa'), (b'OC', 'Orden de Compra'), (b'TC', 'Tarjeta Cr\xe9dito'), (b'TB', 'Transferencia Bancaria')], max_length=200)),
                ('poliza', models.CharField(blank=True, max_length=200)),
                ('certificado', models.CharField(blank=True, max_length=200)),
                ('aseguradora', models.CharField(blank=True, max_length=200)),
                ('deposito', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('admision', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('autorizacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hospitalizacion', models.DateTimeField(blank=True, null=True)),
                ('ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_alta', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[(b'A', b'Admitido'), (b'B', b'Autorizado'), (b'H', b'Hospitalizar'), (b'I', b'Ingresado'), (b'C', b'Alta'), (b'Q', b'Cancelada')], max_length=1)),
                ('tiempo', models.IntegerField(blank=True, default=0)),
                ('neonato', models.NullBooleanField()),
                ('tipo_de_ingreso', models.CharField(blank=True, choices=[(b'PA', b'Particular'), (b'SN', b'Aseguradora Nacional'), (b'SI', b'Aseguradora Internacional'), (b'PS', b'Presupuesto')], max_length=200, null=True)),
                ('facturada', models.NullBooleanField(default=False)),
                ('ultimo_cobro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('admitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fiadores', models.ManyToManyField(blank=True, related_name='fianzas', to='persona.Persona')),
            ],
            options={
                'permissions': (('admision', 'Permite al usuario gestionar admision'),),
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('recibo', models.IntegerField(blank=True, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='spital.Admision')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(blank=True, choices=[(b'N', b'Normal'), (b'S', b'Suite'), (b'U', b'U.C.I.')], max_length=1)),
                ('estado', models.CharField(blank=True, choices=[(b'D', b'Disponible'), (b'O', b'Ocupada'), (b'M', b'Mantenimiento')], max_length=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='inventory.ItemTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='PreAdmision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('completada', models.BooleanField(default=False)),
                ('transferir_cobros', models.BooleanField(default=False)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preadmisiones', to='emergency.Emergencia')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='admision',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admisiones', to='spital.Habitacion'),
        ),
        migrations.AddField(
            model_name='admision',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admisiones', to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='admision',
            name='referencias',
            field=models.ManyToManyField(blank=True, related_name='referencias', to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='admision',
            name='tipo_de_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.TipoVenta'),
        ),
    ]
