# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('S', 'Suite'), ('', 'U.C.I.')], max_length=1),
        ),
    ]
