# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsc', '0001_initial'),
        ('clinique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique.Consulta'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Encuesta'),
        ),
        migrations.AddField(
            model_name='queja',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Respuesta'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Extra'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Encuesta'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Pregunta'),
        ),
        migrations.AddField(
            model_name='meta',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.ScoreCard'),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extra',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.ScoreCard'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Meta'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escala',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.ScoreCard'),
        ),
        migrations.AddField(
            model_name='archivonotas',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Meta'),
        ),
    ]
