# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20160215_0804'),
        ('bsc', '0002_auto_20160115_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
