# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 23:28
from __future__ import unicode_literals

from django.db import migrations


def add_persona(apps, schema_editor):
    Respuesta = apps.get_model('bsc', 'Respuesta')
    for row in Respuesta.objects.select_related('consulta').all():
        row.persona = row.consulta.persona
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('bsc', '0003_respuesta_persona'),
    ]

    operations = [
        migrations.RunPython(
                add_persona,
                reverse_code=migrations.RunPython.noop
        )
    ]
