# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0010_consulta_no_desea_encuesta'),
        ('bsc', '0004_auto_20160222_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rellamar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique.Consulta')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Encuesta')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='meta',
            name='tipo_meta',
            field=models.CharField(choices=[('CT', 'Tiempo de Consulta'), ('PCT', 'Tiempo en Preconsulta'), ('PP', 'Porcentaje de Recetas'), ('IP', 'Porcentaje de Incapacidades'), ('CFP', 'Porcentaje de Aprobaci\xf3n del Cliente'), ('CR', 'Consulta Remitida a Especialista'), ('CO', 'Coaching'), ('P', 'Puntualidad'), ('QJ', 'Manejo de Quejas'), ('VE', 'Ventas del Mes'), ('PR', 'Manejo de Presupuesto'), ('T', 'Manejo de Turnos'), ('TE', 'Horas Ense\xf1adas'), ('EV', 'Evaluaci\xf3n de Alumnos'), ('CA', 'Capacitaciones')], default='CT', max_length=3),
        ),
    ]
