# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0006_auto_20160226_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queja',
            options={'ordering': ['created']},
        ),
    ]
