# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0007_auto_20160227_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solucion',
            options={'ordering': ['queja__created']},
        ),
        migrations.AddField(
            model_name='solucion',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solucion',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
