# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0008_auto_20160227_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
