# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_mastercontract_privado'),
        ('bsc', '0009_encuesta_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Aseguradora'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bsc.Respuesta'),
        ),
    ]
