# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0010_auto_20160308_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='invalida',
            field=models.BooleanField(default=False),
        ),
    ]
