# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0011_respuesta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='notificada',
            field=models.BooleanField(default=False),
        ),
    ]
