# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinique', '0029_auto_20161101_2339'),
        ('bsc', '0013_queja_usuario_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoResponde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique.Consulta')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Encuesta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='rellamar',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
