# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import emergency.models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0014_auto_20161107_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='tipo_extra',
            field=models.CharField(choices=[('ER', 'Emergencias Atendidas'), ('EV', 'Evaluación del Estudiante')], default=emergency.models.Emergencia, max_length=3),
        ),
    ]
