# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0032_consulta_encuestada_seguimiento'),
        ('bsc', '0015_auto_20161119_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='relconsultas',
            field=models.ManyToManyField(to='clinique.Consulta'),
        ),
    ]
