# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0016_encuesta_relconsultas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='relconsultas',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='satisfaccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='seguimiento',
            field=models.BooleanField(default=False),
        ),
    ]
