# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('persona', '0003_auto_20160130_1001'),
        ('clinique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='examen',
                name='persona',
                field=models.ForeignKey(blank=True, null=True,
                                        on_delete=django.db.models.deletion.CASCADE,
                                        related_name='clinique_examenes',
                                        to='persona.Persona'),
        ),
    ]
