# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0003_auto_20160130_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='paciente',
        ),
    ]
