# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0004_remove_examen_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='consultorio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
