# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0008_auto_20160217_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['created']},
        ),
    ]
