# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0009_auto_20160218_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='no_desea_encuesta',
            field=models.BooleanField(default=False),
        ),
    ]
