# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_mastercontract_privado'),
        ('clinique', '0010_consulta_no_desea_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Contrato'),
        ),
    ]
