# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:53
from __future__ import unicode_literals

from django.db import migrations


def add_contrato(apps, schema_editor):
    Consulta = apps.get_model('clinique', 'Consulta')
    for consulta in Consulta.objects.select_related('persona').all():
        if consulta.contrato is None and consulta.poliza:
            contrato = consulta.persona.contratos.filter(
                master=consulta.poliza
            ).first()
            if contrato is None:
                beneficiario = consulta.persona.beneficiarios.filter(
                    contrato__master=consulta.poliza
                ).first()
                if beneficiario is not None:
                    contrato = beneficiario.contrato

            consulta.contrato = contrato
            consulta.save()


class Migration(migrations.Migration):
    dependencies = [
        ('clinique', '0011_consulta_contrato'),
    ]

    operations = [
        migrations.RunPython(
            add_contrato,
            reverse_code=migrations.RunPython.noop
        )
    ]
