# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0012_auto_20160227_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinique.TipoConsulta'),
        ),
    ]
