# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 14:59
from __future__ import unicode_literals

from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0013_cita_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='duracion',
            field=models.DurationField(default=timedelta),
        ),
    ]
