# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 15:05
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Consulta = apps.get_model("clinique", "Consulta")
    for consulta in Consulta.objects.all():
        if consulta.final and consulta.final > consulta.created:
            consulta.duracion = consulta.final - consulta.created
            consulta.save()


class Migration(migrations.Migration):
    dependencies = [
        ('clinique', '0014_consulta_duracion'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
