# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 02:07
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Espera = apps.get_model("clinique", "Espera")
    for espera in Espera.objects.all():
        if espera.consultorio and espera.consultorio.secretaria:
            espera.usuario = espera.consultorio.secretaria
            espera.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0016_espera_usuario'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
