# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0017_auto_20160310_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afeccion',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
