# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0018_auto_20160311_1300'),
        ('clinique', '0017_auto_20160310_2007'),
    ]

    operations = [
    ]
