# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_nombre_comercial'),
        ('clinique', '0019_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Ciudad'),
        ),
    ]
