# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0020_localidad_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='orl',
            new_name='descripcion_orl',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='aspecto_general',
            field=models.CharField(blank=True, choices=[('L', 'Lucido'), ('C', 'Consciente'), ('O', 'Orientado')], max_length=1),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='cabeza',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('A', 'Anormal')], max_length=1),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='cuello',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('A', 'Anormal')], max_length=1),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='ojos',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('A', 'Anormal')], max_length=1),
        ),
    ]
