# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0021_auto_20160317_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='orl',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('A', 'Anormal')], max_length=1),
        ),
    ]
