# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0024_auto_20160318_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultorio',
            options={'ordering': ['nombre'], 'permissions': (('consultorio', 'Permite al usuario gestionar consultorios'), ('clinical_read', 'Permite que el usuario tenga acceso a los consultorios'))},
        ),
    ]
