# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0025_auto_20160411_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultorio',
            options={'ordering': ['nombre'], 'permissions': (('consultorio', 'Permite al usuario gestionar consultorios'), ('clinical_read', 'Permite que el usuario tenga acceso a los datos cl\xednicos'), ('clinical_write', 'Permite que el usuario escriba a los datos cl\xednicos'))},
        ),
    ]
