# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 02:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_persona_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinique', '0026_ordenlaboratorio_ordenlaboratorioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsperaDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion', models.DurationField(default=datetime.timedelta)),
                ('terminada', models.BooleanField(default=False)),
                ('espera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_datos', to='clinique.Espera')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espera_datos', to='persona.Persona')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='EsperaDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion', models.DurationField(default=datetime.timedelta)),
                ('terminada', models.BooleanField(default=False)),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_doctor', to='clinique.Consultorio')),
                ('espera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_doctor', to='clinique.Espera')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espera_doctor', to='persona.Persona')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='EsperaEnfermeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion', models.DurationField(default=datetime.timedelta)),
                ('terminada', models.BooleanField(default=False)),
                ('espera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_enf', to='clinique.Espera')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espera_enf', to='persona.Persona')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='EsperaSap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion', models.DurationField(default=datetime.timedelta)),
                ('terminada', models.BooleanField(default=False)),
                ('espera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_sap', to='clinique.Espera')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espera_sap', to='persona.Persona')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
