# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0027_auto_20160827_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afeccion',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='adjunto',
            field=models.FileField(upload_to='clinique/examen/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(upload_to='consultorio/reports/%Y/%m/%d'),
        ),
    ]
