# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_company_incapacidad_image'),
        ('clinique', '0027_auto_20160827_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='espera',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Ciudad'),
        ),
    ]
