# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0027_esperadatos_esperadoctor_esperaenfermeria_esperasap'),
    ]

    operations = [
        migrations.AddField(
            model_name='espera',
            name='datos',
            field=models.BooleanField(default=False),
        ),
    ]
