# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0028_espera_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultorio',
            options={'ordering': ['nombre'], 'permissions': (('consultorio', 'Permite al usuario gestionar consultorios'), ('clinical_read', 'Permite que el usuario tenga acceso a los datos cl\xednicos'), ('clinical_write', 'Permite que el usuario escriba a los datos cl\xednicos'), ('clinical_manage', 'Permite que el usuario escriba a los datos cl\xednicos'))},
        ),
    ]
