# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0029_auto_20161101_2339'),
        ('clinique', '0028_auto_20161005_1311'),
    ]

    operations = [
    ]
