# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0030_consulta_call_center'),
        ('clinique', '0030_merge_20161108_1831'),
    ]

    operations = [
    ]
