# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0031_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='encuestada_seguimiento',
            field=models.BooleanField(default=False),
        ),
    ]
