# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0031_auto_20160822_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperadatos',
            name='espera',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_datos', to='clinique.Espera'),
        ),
        migrations.AlterField(
            model_name='esperadoctor',
            name='espera',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_doctor', to='clinique.Espera'),
        ),
        migrations.AlterField(
            model_name='esperaenfermeria',
            name='espera',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_enf', to='clinique.Espera'),
        ),
        migrations.AlterField(
            model_name='esperasap',
            name='espera',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espera_sap', to='clinique.Espera'),
        ),
    ]
