# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160411_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventario'),
        ),
        migrations.AddField(
            model_name='itemcomprado',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
