# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemtemplate_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='transferida',
        ),
        migrations.AlterField(
            model_name='item',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventario'),
        ),
    ]
