# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20160502_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='inventory/compra/comprobante/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_de_pago',
            field=models.FileField(blank=True, null=True, upload_to='inventory/compra/pago/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcomprado',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Compra'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='entregada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
