# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventario_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtemplate',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='itemtemplate',
            name='comision2',
        ),
    ]
