# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160511_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicion',
            old_name='aprobada',
            new_name='denegada',
        ),
    ]
