# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20160513_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='puede_comprar',
            field=models.BooleanField(default=False),
        ),
    ]
