# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_anomaliatransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='precio_de_venta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
