# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20160116_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('created',), 'permissions': (('persona', 'Permite al usuario gestionar persona'),)},
        ),
        migrations.AlterField(
            model_name='persona',
            name='mostrar_en_cardex',
            field=models.BooleanField(default=False, verbose_name='Es representante legal'),
        ),
    ]
