# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20160130_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('D', 'Divorciado/a'), ('C', 'Casado/a'), ('U', 'Union Libre'), ('', '---------')], max_length=1),
        ),
    ]
