# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20160215_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='fisico',
            name='bmr',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='fisico',
            name='medida_de_peso',
            field=models.CharField(blank=True, choices=[('Lb', 'Libras'), ('Kg', 'Kilogramos')], default='Lb', max_length=2),
        ),
        migrations.AddField(
            model_name='historiafisica',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='historiafisica',
            name='bmr',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='historiafisica',
            name='medida_de_peso',
            field=models.CharField(blank=True, choices=[('Lb', 'Libras'), ('Kg', 'Kilogramos')], default='Lb', max_length=2),
        ),
    ]
