# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:48
from __future__ import unicode_literals

from decimal import Decimal

from datetime import date
from django.db import migrations


def obtener_edad(persona):
    """Obtiene la edad de la :class:`Persona`"""

    if persona.nacimiento is None:
        return None

    today = date.today()
    born = persona.nacimiento
    return today.year - born.year - (
        (today.month, today.day) < (born.month, born.day))


def get_weight(historia):
    if historia.medida_de_peso == 'Lb':
        return historia.peso / Decimal(2.22)
    else:
        return historia.peso


def body_mass_index(historia):
    return get_weight(historia) / historia.altura


def basal_energetic_expense(historia):
    if historia.persona.sexo == 'M':
        return Decimal(66.5) + Decimal(13.75) * get_weight(historia) + \
               Decimal(5) * historia.altura * 100 + \
               Decimal(6.78) * obtener_edad(historia.persona)
    else:
        return Decimal(655.1) + Decimal(9.56) * get_weight(historia) + \
               Decimal(1.85) * historia.altura * 100 + \
               Decimal(4.68) * obtener_edad(historia.persona)


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    HistoriaFisica = apps.get_model("persona", "HistoriaFisica")
    for historia in HistoriaFisica.objects.all():
        if historia.peso is None:
            continue
        if historia.altura != Decimal():
            historia.bmi = body_mass_index(historia)
        bmr = basal_energetic_expense(historia)
        historia.bmr = bmr
        historia.save()


class Migration(migrations.Migration):
    dependencies = [
        ('persona', '0005_auto_20160321_1547'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
