# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:33
from __future__ import unicode_literals

import decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20160322_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal, max_digits=5),
        ),
    ]
