# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 00:48
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20160322_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedente',
            name='persona',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='antecedentefamiliar',
            name='persona',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='antecedente_familiar', serialize=False, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='antecedenteobstetrico',
            name='persona',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='antecedente_obstetrico', serialize=False, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='estilovida',
            name='persona',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estilo_vida', serialize=False, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='fisico',
            name='persona',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='persona.Persona'),
        ),
    ]
