# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20160323_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiafisica',
            name='presion_arterial_media',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historiafisica',
            name='presion_diastolica',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historiafisica',
            name='presion_sistolica',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historiafisica',
            name='pulso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historiafisica',
            name='respiracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historiafisica',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
