# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencia',
            name='tipo_de_venta',
        ),
        migrations.AddField(
            model_name='emergencia',
            name='presion_arterial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
