# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to=b'lab/results/%Y/%m/%d')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='persona.Persona')),
            ],
            options={
                'permissions': (('lab', 'Permite al usuario administrar laboratorios'),),
            },
        ),
    ]
