# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('fecha_de_deposito', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('aplicado', models.BooleanField(default=False)),
                ('comprobante', models.FileField(upload_to='income/deposito/%Y/%m/%d')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Pago')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('deposito_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='income.Deposito')),
                ('fecha_de_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_de_cheque', models.CharField(max_length=255)),
                ('monto_retenido', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('banco_de_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.Banco')),
                ('emisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=('income.deposito',),
        ),
        migrations.CreateModel(
            name='CierrePOS',
            fields=[
                ('deposito_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='income.Deposito')),
                ('batch', models.CharField(max_length=255)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.Banco')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=('income.deposito',),
        ),
        migrations.AddField(
            model_name='deposito',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Fuente'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepago',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='income.Cheque'),
        ),
    ]
