# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='cheque',
                name='imagen_de_cheque',
                field=models.FileField(null=True,
                                       upload_to='income/cheque/%Y/%m/%d'),
        ),
        migrations.AddField(
                model_name='cheque',
                name='monto2',
                field=models.DecimalField(decimal_places=2, default=0,
                                          max_digits=11),
        ),
        migrations.AddField(
                model_name='cheque',
                name='new_id',
                field=models.IntegerField(default=0),
        ),
        migrations.AddField(
                model_name='cheque',
                name='usuario2',
                field=models.ForeignKey(null=True,
                                        on_delete=django.db.models.deletion.CASCADE,
                                        to=settings.AUTH_USER_MODEL),
        )
    ]
