# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='monto_retenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
