# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='monto2',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='usuario2',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='cheque',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 16, 18, 59, 57, 549000, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 16, 19, 0, 2, 235000, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheque',
            name='new_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
