# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:44
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Cheque = apps.get_model("income", "Cheque")
    for cheque in Cheque.objects.all():
        cheque.new_id = cheque.id
        cheque.usuario2 = cheque.usuario
        cheque.monto2 = cheque.monto
        cheque.imagen_de_cheque = cheque.comprobante
        cheque.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20160116_1236'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
