# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20160116_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque',
            old_name='new_id',
            new_name='id',
        ),
    ]
