# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_cheque_monto_retenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='cuenta_por_cobrar',
        ),
    ]
