# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_auto_20160116_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
