# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_historiafisica'),
        ('income', '0003_remove_cheque_cuenta_por_cobrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepago',
            name='deposito',
        ),
        migrations.AddField(
            model_name='cheque',
            name='emisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='detallepago',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='income.Cheque'),
        ),
    ]
