# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_auto_20160116_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={},
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='deposito_ptr',
        ),
        migrations.AlterField(
            model_name='cheque',
            name='new_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
