# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:39
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import persona.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0001_initial'),
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteDeduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('correlativo', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ciudad')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Proveedor')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='ConceptoDeduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('descripcion', models.TextField(blank=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.ComprobanteDeduccion')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemTemplate')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('facturada', models.BooleanField(default=False)),
                ('credito', models.BooleanField(default=False)),
                ('terminada', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Ciudad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
                ('tipo_de_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.TipoVenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('cajero', 'Permite al usuario gestionar caja'),),
            },
        ),
        migrations.CreateModel(
            name='Cotizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_descuento', models.IntegerField(default=0)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('descontable', models.BooleanField(default=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Cotizacion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemTemplate')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('descripcion', models.TextField()),
                ('minimum', models.DateTimeField(default=django.utils.timezone.now)),
                ('inicial', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('enviadas', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='DetalleCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemTemplate')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('correlativo', models.IntegerField(default=0)),
                ('motivo_de_emision', models.CharField(blank=True, choices=[('AN', 'Anulaci\xf3n'), ('DV', 'Devoluci\xf3n'), ('DE', 'Descuento')], max_length=1)),
                ('cerrada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('completada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('comprobante', models.CharField(blank=True, max_length=255, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Aseguradora')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='PagoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.CuentaPorCobrar')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('correlativo', models.IntegerField(default=0)),
                ('credito', models.BooleanField(default=False)),
                ('cerrado', models.BooleanField(default=False)),
                ('nulo', models.BooleanField(default=False)),
                ('emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to=settings.AUTH_USER_MODEL)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='users.Ciudad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='persona.Persona')),
                ('tipo_de_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.TipoVenta')),
            ],
            options={
                'permissions': (('cajero', 'Permite al usuario gestionar caja'),),
            },
        ),
        migrations.CreateModel(
            name='StatusPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('reportable', models.BooleanField(default=True)),
                ('pending', models.BooleanField(default=False)),
                ('next_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.StatusPago')),
                ('previous_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='invoice.StatusPago')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('color', persona.fields.ColorField(default='', max_length=10)),
                ('solo_asegurados', models.BooleanField(default=False)),
                ('reembolso', models.BooleanField(default=False)),
                ('reportable', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('apertura', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('finalizado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('descuento', models.IntegerField(default=0)),
                ('descontable', models.BooleanField(default=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='inventory.ItemTemplate')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='invoice.Recibo')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='invoice.Recibo'),
        ),
        migrations.AddField(
            model_name='pago',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='invoice.StatusPago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='invoice.TipoPago'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Recibo'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Recibo'),
        ),
        migrations.AddField(
            model_name='detallecredito',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.NotaCredito'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.StatusPago'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cierreturno',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='invoice.TipoPago'),
        ),
        migrations.AddField(
            model_name='cierreturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='invoice.TurnoCaja'),
        ),
    ]
