# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizado',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='cuentaporcobrar',
            options={'ordering': ('-created',)},
        ),
    ]
