# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20160128_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantededuccion',
            name='cai',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprobantededuccion',
            name='cai_proveedor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprobantededuccion',
            name='fecha_de_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comprobantededuccion',
            name='fin_rango',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comprobantededuccion',
            name='inicio_rango',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comprobantededuccion',
            name='numero_de_documento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
