# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20160201_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
