# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20160204_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='month_offset',
            field=models.IntegerField(default=0),
        ),
    ]
