# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_recibo_month_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopago',
            name='mensual',
            field=models.BooleanField(default=False),
        ),
    ]
