# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160328_1723'),
        ('invoice', '0006_tipopago_mensual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantededuccion',
            name='cai',
        ),
        migrations.RemoveField(
            model_name='comprobantededuccion',
            name='fin_rango',
        ),
        migrations.RemoveField(
            model_name='comprobantededuccion',
            name='inicio_rango',
        ),
        migrations.AddField(
            model_name='comprobantededuccion',
            name='legal_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.LegalData'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='legal_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.LegalData'),
        ),
        migrations.AddField(
            model_name='recibo',
            name='legal_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.LegalData'),
        ),
    ]
