# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 23:36
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Recibo = apps.get_model("invoice", "Recibo")
    ComprobanteDeduccion = apps.get_model("invoice", "ComprobanteDeduccion")
    NotaCredito = apps.get_model("invoice", "NotaCredito")

    for recibo in Recibo.objects.all():
        recibo.legal_data = recibo.ciudad.recibo
        recibo.save()

    for nota in NotaCredito.objects.all():
        nota.legal_data = nota.ciudad.nota_credito
        nota.save()

    for comprobante in ComprobanteDeduccion.objects.all():
        comprobante.legal_data = comprobante.ciudad.comprobante
        comprobante.save()


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0007_auto_20160328_1723'),
        ('users', '0005_auto_20160328_1747'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
