# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20160630_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizado',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
