# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20151203_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
