# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20150922_1309'),
        ('invoice', '0012_pago_completado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemTemplate')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('correlativo', models.IntegerField(default=0)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Recibo')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='detallecredito',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.NotaCredito'),
        ),
    ]
