# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20151228_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='motivo_de_emision',
            field=models.CharField(blank=True, choices=[('AN', 'Anulaci\xf3n'), ('DV', 'Devoluci\xf3n'), ('DE', 'Descuento')], max_length=1),
        ),
    ]
